apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    # This URL works inside the cluster — Grafana talks to Prometheus via service DNS
    url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      httpMethod: POST
